crud_movies/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

crud_movies/movies_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

crud_movies/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.TextField()
    title_en = models.TextField()
    audience = models.IntegerField()
    open_date = models.DateTimeField(None)
    genre = models.TextField()
    watch_grade = models.TextField()
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()

crud_movies/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {'movies': movies}
    return render(request, 'movies/index.html', context)

def create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        title_en = request.POST.get('title_en')
        audience = request.POST.get('audience')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        watch_grade = request.POST.get('watch_grade')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')
        movie = Movie(
            title=title,
            title_en=title_en,
            audience=audience,
            open_date=open_date,
            genre=genre,
            watch_grade=watch_grade,
            score=score,
            poster_url=poster_url,
            description=description
        )
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        return render(request, 'movies/create.html')

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {'movie': movie}
    return render(request, 'movies/detail.html', context)

def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('movies:index')
    else:
        return redirect('movies:detail', movie.pk)

def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        movie.title = request.POST.get('title')
        movie.title_en = request.POST.get('title_en')
        movie.audience = request.POST.get('audience')
        movie.open_date = request.POST.get('open_date')
        movie.genre = request.POST.get('genre')
        movie.watch_grade = request.POST.get('watch_grade')
        movie.score = request.POST.get('score')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        context = {'movie': movie}
        return render(request, 'movies/update.html', context)

crud_movies/movies/templates/movies/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

crud_movies/movies/templates/movies/create.html
{% extends 'movies/base.html' %}
{% block content %}
<h1>NEW</h1>
<!--<form action="/boards/create/" method="POST">-->
<form action="" method="POST">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title"><br>
    <label for="title_en">TITLE_EN</label>
    <input type="text" name="title_en" id="title_en"><br>
    <label for="audience">AUDIENCE</label>
    <input type="number" name="audience" id="audience"><br>
    <label for="open_date">OPEN_DATE</label>
    <input type="date" name="open_date" id="open_date"><br>
    <label for="genre">GENRE</label>
    <input type="text" name="genre" id="genre"><br>
    <label for="watch_grade">WATCH_GRADE</label>
    <input type="text" name="watch_grade" id="watch_grade"><br>
    <label for="score">SCORE</label>
    <input type="number" name="score" id="score"><br>
    <label for="poster_url">POSTER_URL</label>
    <input type="text" name="poster_url" id="poster_url"><br>
    <label for="description">DESCRIPTION</label>
    <textarea name="description" id="description"></textarea>
    <input type="submit" value="작성">
</form>

<a href="{% url 'movies:index' %}">back</a>
{% endblock %}

crud_movies/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block content %}
    <h1>DETAIL</h1>
    <hr>
    <p>제목: {{movie.title}}</p>
    <p>제목(영어): {{movie.title_en}}</p>
    <p>누적 관객수: {{movie.audience}}</p>
    <p>개봉일: {{movie.open_date}}</p>
    <p>장르: {{movie.genre}}</p>
    <p>관람등급: {{movie.watch_grade}}</p>
    <p>평점: {{movie.score}}</p>
    <p>포스터 이미지 URL: {{movie.poster_url}}</p>
    <p>영화소개: {{movie.description}}</p>
    <a href="{% url 'movies:update' movie.pk %}">[수정]</a>
    <form action="{% url 'movies:delete' movie.pk %}" method="POST" style="display: inline" onsubmit="return confirm('R U SURE??')">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>

    <br>
    <a href="{% url 'movies:index' %}">메인 페이지</a>
{% endblock %}

crud_movies/movies/templates/movies/index.html
{% extends 'movies/base.html' %}
{% block content %}
    <a href="{% url 'movies:create' %}">글 작성</a>
    <hr>
    {% for movie in movies %}
        <p>{{movie.title}}</p>
        <p>{{movie.score}}</p>
        <a href="{% url 'movies:detail' movie.pk %}">글 보러가기</a>
        <hr>
    {% endfor %}
{% endblock %}

crud_movies/movies/templates/movies/update.html
{% extends 'movies/base.html' %}
{% block content %}
<h1>EDIT</h1>
<!--<form action="/boards/create/" method="POST">-->
<form action="" method="POST">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title" value="{{ movie.title }}"><br>
    <label for="title_en">TITLE_EN</label>
    <input type="text" name="title_en" id="title_en" value="{{ movie.title_en }}"><br>
    <label for="audience">AUDIENCE</label>
    <input type="number" name="audience" id="audience" value="{{ movie.audience }}"><br>
    <label for="open_date">OPEN_DATE</label>
    <input type="date" name="open_date" id="open_date" value="{{movie.open_date}}"><br>
    <label for="genre">GENRE</label>
    <input type="text" name="genre" id="genre" value="{{movie.genre}}"><br>
    <label for="watch_grade">WATCH_GRADE</label>
    <input type="text" name="watch_grade" id="watch_grade" value="{{movie.watch_grade}}"><br>
    <label for="score">SCORE</label>
    <input type="number" name="score" id="score" value="{{movie.score}}"><br>
    <label for="poster_url">POSTER_URL</label>
    <input type="text" name="poster_url" id="poster_url" value="{{movie.poster_url}}"><br>
    <label for="description">DESCRIPTION</label>
    <textarea name="description" id="description">{{movie.description}}</textarea>
    <input type="submit" value="수정">
</form>

<a href="{% url 'movies:detail' movie.pk %}">back</a>
{% endblock %}