crud_intro/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:board_pk>/update/', views.update, name='update'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete')
]

crud_intro/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud_intro/boards/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.
class Board(models.Model):
    # id (pk) 는 기본적으로 처음 테이블 생성시 자동 생성된다.
    # id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = ProcessedImageField(
        upload_to='boards/images', # 저장 위치 (media 이후의 경로)
        processors=[Thumbnail(200, 300)], # 처리할 작업 목록
        format='JPEG', # 저장 목록
        options={'quality': 90}, # 추가 옵션

    )
    # auto_now_add : 생성일자 / db 가 최초 저장시에만 적용
    # auto_now : 수정일자 / db가 새로 저장될때마다 갱신
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.id}글 - {self.title}: {self.content}'

class Comment(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'<Board({self.board_id}): Comment({self.pk} - {self.content})>'

crud_intro/boards/views.py
from django.shortcuts import render, redirect
from .models import Board, Comment
from IPython import embed

# Create your views here.

def index(request):
    boards = Board.objects.all()
    context = {'boards': boards}
    return render(request, 'boards/index.html', context)

# def new(request):
#     return render(request, 'boards/create.html')

def create(request):
    # embed()
    # new에서 넘어오는 제목과 내용을 저장
    # orm title 과 content에 위에서 넘어온 값을 할당
    # db에 저장
    # create.html 페이지를 render

    if request.method == 'POST':
        # request method 가 POST로 있을 때는 create
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        board = Board(title=title, content=content, image=image)
        board.save()
        # return redirect(f'/boards/{board.pk}/')
        return redirect('boards:detail', board.pk)
        # request method가 GET으로 있을 때는 new
    else:
        return render(request, 'boards/create.html')

def detail(request, board_pk):
    # 요청으로 들어온 pk 값으로 해당 글을 찾아옴
    board = Board.objects.get(pk=board_pk)
    # comments = board.comment_set.all()
    comments = board.comment_set.order_by('-pk')
    context = {
        'board': board,
        'comments': comments,
    }
    return render(request, 'boards/detail.html', context)

def delete(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail', board.pk)

# def edit(request, pk):
#     board = Board.objects.get(pk=pk)
#     context = {'board': board}
#     return render(request, 'boards/update.html', context)

def update(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.image = request.FILES.get('image')
        board.save()
        #return redirect(f'/boards/{board.pk}/')
        return redirect('boards:detail', board.pk)
    else:
        context = {'board': board}
        return render(request, 'boards/update.html', context)

def comments_create(request, board_pk):
    # 댓글을 달 게시물
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        # form에서 날아온 댓글 정보
        content = request.POST.get('content')
        # 댓글 생성 및 지정
        comment = Comment(board=board, content=content)
        comment.save()
        return redirect('boards:detail', board.pk)
    else:
        return redirect('boards:detail', board.pk)

def comments_delete(request, board_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
    return redirect('boards:detail', board_pk)

crud_intro/boards/templates/boards/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--<link rel="shortcut icon" type="image/png" href="{% static 'boards/images/football.png' %}">-->
    <link rel="shortcut icon" href="{% static 'boards/images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'boards/images/favicon.ico' %}" type="image/x-icon">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

crud_intro/boards/templates/boards/create.html
{% extends 'boards/base.html' %}
{% load static %}
{% block content %}
<h1>NEW</h1>
<!--<form action="/boards/create/" method="POST">-->
<img src="{% static 'sample2.jpg' %}" alt="sample_img">
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" name="title" id="title"><br>
    <label for="content">CONTENT</label>
    <textarea name="content" id="content"></textarea><br>
    <input type="file" name="image" accept="image/*"><br>
    <input type="submit" value="작성">
</form>
<!--<a href="/boards/">back</a>-->
<a href="{% url 'boards:index' %}">back</a>
{% endblock %}

crud_intro/boards/templates/boards/detail.html
{% extends 'boards/base.html' %}
{% load static %}
{% block content %}
    <h1>DETAIL</h1>
    {% if board.image %}
        <img src="{{ board.image.url }}" alt="{{board.image}}">
    {% else %}
        <img src="{% static 'boards/images/no_image.png' %}" alt="no-image">
    {% endif %}
    <h2>{{board.pk}} 번째 글</h2>
    <hr>
    <p>제목: {{board.title}}</p>
    <p>내용: {{board.content}}</p>
    <p>작성 시각: {{board.created_at}}</p>
    <p>수정 시각: {{board.updated_at}}</p>
    <hr>
    <!-- 댓글 출력 -->
    <p>{{ comments | length }} 개의 댓글</p>

    {% for comment in comments %}
        <li>
            {{comment.content}}
            <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST" style="display: inline">
                {% csrf_token %}
                <input type="submit" value="삭제">
            </form>
        </li>
    {% empty %}
        <p><b>댓글이 없어요..</b></p>
    {% endfor %}
    <hr>
    <!-- 댓글 입력 -->
    <form action="{% url 'boards:comments_create' board.pk %}" method="POST">
        {% csrf_token %}
        <label for="content">Comment</label>
        <input type="text" name="content" id="content">
        <input type="submit" value="submit">
    </form>
    <hr>
    <!--<a href="/boards/{{ board.pk }}/edit/">[수정]</a>-->
    <!--<a href="/boards/{{ board.pk }}/delete/">[삭제]</a>-->
    <a href="{% url 'boards:update' board.pk %}">[수정]</a>
    <form action="{% url 'boards:delete' board.pk %}" method="POST" style="display: inline" onsubmit="return confirm('R U SURE??')">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form><br>
    <!--<a href="/boards/">메인 페이지</a>-->
    <a href="{% url 'boards:index' %}">메인 페이지</a>
{% endblock %}

crud_intro/boards/templates/boards/index.html
{% extends 'boards/base.html' %}
{% load static %}
{% block content %}
    <h1>안녕하세요</h1>
    <img src="{% static 'boards/images/sample_img.jpg' %}" alt="sample_img">
    <!--<a href="/boards/new/">글 작 성</a>-->
    <a href="{% url 'boards:create' %}">글 작성</a>
    <hr>
    {% for board in boards %}
        <p>{{board.pk}}</p>
        <p>{{board.title}}</p>
        <p>{{board.created_at|timesince}} 전 </p>
        <!--<a href="/boards/{{board.pk}}/">글 보러가기</a>-->
        <a href="{% url 'boards:detail' board.pk %}">글 보러가기</a>
        <hr>
    {% endfor %}
{% endblock %}

crud_intro/boards/templates/boards/update.html
{% extends 'boards/base.html' %}
{% load static %}
{% block content %}
<h1>EDIT</h1>
<!--<form action="/boards/{{board.pk}}/update/" method="POST">-->
    {% if board.image %}
        <img src="{{ board.image.url }}" alt="{{board.image}}">
    {% else %}
        <img src="{% static 'boards/images/no_image.png' %}" alt="no-image">
    {% endif %}
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <label for="title">TITLE</label>
        <input type="text" name="title" id="title" value="{{ board.title }}"><br>
        <label for="content">CONTENT</label>
        <textarea name="content" id="content">{{ board.content }}</textarea>
        <input type="file" name="image" accept="image/*">
        <input type="submit" value="수정">
    </form>
<!--<a href="/boards/{{board.pk}}/">back</a>-->
<a href="{% url 'boards:detail' board.pk %}">back</a>
{% endblock %}