crud_movies2/movies/urls.py
from django.urls import path
from . import views
app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/scores/', views.scores_create, name='scores_create'),
    path('<int:movie_pk>/scores/<int:score_pk>/delete/', views.scores_delete, name='scores_delete'),
]

crud_movies2/movies_porject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

crud_movies2/movies/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.TextField()

class Movie(models.Model):
    title = models.TextField()
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

class Score(models.Model):
    content = models.TextField()
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

crud_movies2/movies/views.py
from django.shortcuts import render, redirect
from .models import Genre, Movie, Score
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies
    }
    return render(request, 'movies/index.html', context)

def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    genre = Genre.objects.get(pk=movie.genre_id)
    scores = movie.score_set.order_by('-pk')
    context = {
        'movie': movie,
        'genre': genre,
        'scores': scores,
    }
    return render(request, 'movies/detail.html', context)

def update(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        movie.title = request.POST.get('title')
        movie.audience = request.POST.get('audience')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        context = {
            'movie': movie,
        }
        return render(request, 'movies/update.html', context)

def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('movies:index')
    else:
        return redirect('movies:detail', movie.pk)

def scores_create(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        content = request.POST.get('content')
        score = request.POST.get('score')
        maked_score = Score(movie=movie, content=content, score=score)
        maked_score.save()
        return redirect('movies:detail', movie.pk)
    else:
        return redirect('movies:detail', movie.pk)

def scores_delete(request, movie_pk, score_pk):
    score = Score.objects.get(pk=score_pk)
    if request.method == 'POST':
        score.delete()
    return redirect('movies:detail', movie_pk)

crud_movies2/movies/templates/movies/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

crud_movies2/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block content %}
    <h2>{{movie.pk}} 번째 영화</h2>
    <hr>
    <p>제목: {{movie.title}}</p>
    <p>누적 관객수: {{movie.audience}}</p>
    <p>포스터 이미지: </p>
    <img src="{{movie.poster_url}}" alt="movie_image">
    <p>영화 소개: {{movie.description}}</p>
    <p>장르: {{genre.name}}</p>

    <!-- 평점 출력 -->
    <p>{{ scores | length }} 개의 평점</p>
    {% for score in scores %}
        <li>
            {{score.content}}
            {{score.score}}
            <form action="{% url 'movies:scores_delete' movie.pk score.pk %}" method="POST" style="display: inline">
                {% csrf_token %}
                <input type="submit" value="삭제">
            </form>
        </li>
    {% empty %}
        <p><b>평점이 없어요..</b></p>
    {% endfor %}
    <hr>

    <!-- 평점 입력 -->
    <form action="{% url 'movies:scores_create' movie.pk %}" method="POST">
        {% csrf_token %}
        <label for="score">Score</label>
        <input type="text" name="score" id="score">

        <label for="content">Content</label>
        <input type="text" name="content" id="content">

        <input type="submit" value="submit">
    </form>
    <hr>

    <a href="{% url 'movies:update' movie.pk %}">[수정]</a>
    <form action="{% url 'movies:delete' movie.pk %}" method="POST" style="display: inline" onsubmit="return confirm('R U SURE??')">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form><br>
    <a href="{% url 'movies:index' %}">[메인으로]</a>
{% endblock %}

crud_movies2/movies/templates/movies/index.html
{% extends 'movies/base.html' %}
{% block content %}
    <h1>영화 목록</h1>
    <hr>
    {% for movie in movies %}
        <div class="container">
            <a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a>
        </div>
        <img src="{{movie.poster_url}}" alt="movie_image">
        <hr>
    {% endfor %}
{% endblock %}

crud_movies2/movies/templates/movies/update.html
{% extends 'movies/base.html' %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="title">TITLE</label>
        <input type="text" name="title" id="title" value="{{movie.title}}"><br>

        <label for="audience">AUDIENCE</label>
        <input type="text" name="audience" id="audience" value="{{movie.audience}}"><br>

        <label for="poster_url">POSTER_URL</label>
        <input type="text" name="poster_url" id="poster_url" value="{{movie.poster_url}}"><br>

        <label for="description">DESCRIPTION</label>
        <input type="text" name="description" id="description" value="{{movie.description}}"><br>
    </form>
<a href="{% url 'movies:detail' movie.pk %}">back</a>
{% endblock %}